basic.forever(function () {
    profont.setRotatation(0)
    profont.setYose(-1)
    profont.showString("1")
    basic.pause(500)
    profont.setYose(0)
    profont.showString("2")
    basic.pause(500)
    profont.setYose(1)
    profont.showString("3")
    basic.pause(500)
    profont.setRotatation(0)
    profont.showString("abc")
    basic.pause(500)
    profont.setRotatation(1)
    profont.showString("abc")
    basic.pause(500)
    profont.setRotatation(2)
    profont.showString("abc")
    basic.pause(500)
    profont.setRotatation(3)
    profont.showString("abc")

    basic.pause(500)

})
